### PR TITLE
feat: Use SafeApprove for ERC20Inbox Initialization

### PR DESCRIPTION
**Pull request by ControlCplusControlV**
In `ERC20Inbox.sol` there is an approve which is just a plain IERC20 function. However, in standard with the rest of the codebase, using a `safeApprove` would allow Tether and non-standard token support. It is already within the OZ library used extensively everywhere else, and would make my life easier. 

```
copypaste@copypastes-MacBook-Pro nitro-contracts % grep -r ".approve(" src
src/bridge/ERC20Inbox.sol:        IERC20(nativeToken).approve(address(bridge), type(uint256).max);
```

It is also the only instance where this is true, so its a relatively simple patch that opens up the use for Tether as a native token. Thank you for your time and understanding . Signed CLA but if you want to make your own branch + force merge go ahead

### CODE REVIEW

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by gzeoneth** [comment]
Not an issue, during init the allowance must be 0 which would not have issue even with token like USDT.

**Comment by ControlCplusControlV** [comment]
Ser, it is an issue, I ran into it during deployment. Solc fails because the approve function signature given tells it to expect a return, and so when return data is not the correct size it and revert, and so you need a safeApprove to explicitly allow a zerosize return

**Comment by gzeoneth** [comment]
> Ser, it is an issue, I ran into it during deployment and this fixes it. Solc fails because the approve function signature given tells it to expect a return, and so when return data is not the correct size it and revert, and so you need a safeApprove to explicitly allow a zerosize return

Oops, you are right. Will look into this and cherrypick your commit. Thanks!

**Pull request closed without merging**
